# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [ ]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.0601249  0.1322197  0.74015383 ... 0.18649302 0.73230273 0.1776223 ]
 [0.96483791 0.72815776 0.75993378 ... 0.16903125 0.9804337  0.77915026]
 [0.69435151 0.43933829 0.40824706 ... 0.361058   0.24044668 0.58555764]
 ...
 [0.09022202 0.68498906 0.34381181 ... 0.93705687 0.84990982 0.54920608]
 [0.26149461 0.30146822 0.86629044 ... 0.17192669 0.92157678 0.46465517]
 [0.79230843 0.40785795 0.33004078 ... 0.32993793 0.0297588  0.57853094]]
[[0.20717379 0.1006351  0.58456781 ... 0.29243006 0.72005515 0.87485747]
 [0.22918801 0.52653311 0.43028607 ... 0.11770445 0.91986578 0.95885352]
 [0.89152644 0.0930533  0.73859988 ... 0.73604286 0.10002979 0.92315162]
 ...
 [0.20682292 0.81522596 0.43430944 ... 0.97426898 0.96152186 0.0014371 ]
 [0.76391525 0.62333701 0.94450852 ... 0.99347575 0.98155309 0.11341241]
 [0.22698963 0.21429995 0.64929543 ... 0.92546069 0.24226706 0.95385652]]


Без использования numpy

In [ ]:
def mult(a, b):
    if len(a[0]) != len(b):
        print("Ошибка - несовместимое количество строк и столбцов")
        return
    else:
        result = [[0 for _ in range(len(a[0]))] for _ in range(len(b))]
        for i in range(len(a)):
            for j in range(len(b[0])):
                for o in range(len(b)):
                    result[i][j] += a[i][o] * b[o][j]
    return result

C использованием numpy

In [ ]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

In [ ]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.58845822 0.36935804 0.03491262] [0.66598661 0.75131573 0.26298963]


In [ ]:
def scalar_product(a,b):
    s = 0
    for i in range(3):
        s += a[i]*b[i]
    return s

In [ ]:
def np_scalar_product(a,b):
    s = np.dot(a,b)
    return s

In [ ]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Потому что нампай это узконаправленный модуль для такого рода задач и он создан чтобы эффективно их решать, иначе в нём не было бы смысла. В частности, методы в нампае реализованы на C, который сам по себе в разы быстрее питона и который в основном и используется для задач, требовательным к скорости выполнения

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  res = None
  d = np.diag(a)
  even_d = d[d % 2 == 0]
  if len(even_d) != 0:
      res = np.sum(even_d)
  else:
      res = 0
  return res

In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[5, 4, 5, 1, 8],
       [3, 9, 9, 7, 1],
       [2, 8, 7, 4, 7],
       [7, 3, 6, 9, 8],
       [9, 2, 2, 7, 5]])

In [ ]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    result = []
    for x in A:
      cumsum = np.cumsum(x)
      s = cumsum / (np.arange(len(x)) + 1)
      result.append(s)
    return result

In [ ]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    result = None
    encoded_elements = []
    current = a[0]
    counter = 1
    counts = []

    for i in range(1, len(a)):
        if a[i] == current:
            counter += 1
        else:
            encoded_elements.append(current)
            counts.append(counter)
            counter = 1
            current = a[i]
    encoded_elements.append(current)
    counts.append(counter)
    result = np.array(encoded_elements), np.array(counts)

    return result

In [ ]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [ ]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    result = None
    x = copy(X)
    for i in range(len(x)):
        if i % 2 != 0:
            x[i] = a
        else:
            x[i] = x[i]**3
    result = np.concatenate((X, x[::-1]))

    return result

In [ ]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)